from setuptools import setup

setup(
    name='ware-house',
    version='',
    packages=['ware_house', 'ware_house.envs'],
    url='',
    license='',
    author='resitberkaybozkurt',
    author_email='resitberkaybozkurt@gmail.com',
    description='MultiAgent RL',
    classifiers=[
        "Programming Language :: Python :: 3.9",
    ],
    install_requires=[
        "numpy",
        "gym>=0.20",
        "AutoROM==0.4.2",
        "AutoROM.accept-rom-license==0.4.2",
        "Markdown==3.4.1",
        "MarkupSafe==2.1.1",
        "Pillow==9.2.0",
        "Werkzeug==2.2.2",
        "absl-py==1.2.0",
        "ale-py==0.7.4",
        "cachetools==5.2.0",
        "certifi==2022.9.24",
        "charset-normalizer==2.1.1",
        "click==8.1.3",
        "cloudpickle==2.2.0",
        "contourpy==1.0.5",
        "cycler==0.11.0",
        "fonttools==4.37.4",
        "google-auth==2.12.0",
        "google-auth-oauthlib==0.4.6",
        "grpcio==1.49.1",
        "gym==0.21.0",
        "gym-notices==0.0.8",
        "idna==3.4",
        "importlib-metadata==4.12.0",
        "importlib-resources==5.9.0",
        "kiwisolver==1.4.4",
        "matplotlib==3.6.0",
        "numpy==1.23.3",
        "oauthlib==3.2.1",
        "opencv-python==4.6.0.66",
        "packaging==21.3",
        "pandas==1.5.0",
        "pip==21.3.1",
        "protobuf==	3.19.6",
        "psutil	==5.9.2",
        "pyasn1	==0.4.8",
        "pyasn1-modules==0.2.8",
        "pygame==2.1.2",
        "pyparsing==3.0.9",
        "python-dateutil==2.8.2",
        "pytz==2022.2.1",
        "requests==2.28.1",
        "requests-oauthlib==1.3.1",
        "rsa==4.9",
        "setuptools==60.2.0",
        "six==1.16.0",
        "stable-baselines3==1.6.1",
        "tensorboard==2.10.1",
        "tensorboard-data-server==0.6.1",
        "tensorboard-plugin-wit==1.8.1",
        "torch==1.12.1",
        "tqdm==4.64.1",
        "typing-extensions==4.3.0",
        "urllib3==1.26.12",
        "wheel==0.37.1",
        "zipp ==3.8.1",
    ],
)
